---
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  # - rbx-18mode
  # - rbx-19mode
  - ruby-head
  - jruby-head
  - ree
env:
  - RAILS_VERSION=~>3.0
  - RAILS_VERSION=~>3.2.0
  - RAILS_VERSION=~>3.1.0
  - RAILS_VERSION=~>3.0.0